// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentGrades.Data;

#nullable disable

namespace StudentGradesProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120222516_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("StudentGrades.Models.Student", b =>
                {
                    b.Property<int>("StudentKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubjectKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentKey");

                    b.HasIndex("SubjectKey");

                    b.ToTable("mst_student", (string)null);
                });

            modelBuilder.Entity("StudentGrades.Models.Subject", b =>
                {
                    b.Property<int>("SubjectKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectKey");

                    b.ToTable("mst_subject", (string)null);
                });

            modelBuilder.Entity("StudentGrades.Models.Student", b =>
                {
                    b.HasOne("StudentGrades.Models.Subject", "Subject")
                        .WithMany("Students")
                        .HasForeignKey("SubjectKey");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentGrades.Models.Subject", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
